# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zawadi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
