# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawadi', '0002_auto_20190529_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='creator',
            field=models.CharField(default='wanjiku', max_length=30),
            preserve_default=False,
        ),
    ]
